### ISSUE TITLE
Add link to Arxiv paper

### ISSUE THREAD

**Issue by impredicative** [ESanchezLozano/GANnotation#1]
I see you have mentioned your Arxiv paper in the readme, but can you also add a link to it? I didn't see one. The link in question is https://arxiv.org/abs/1811.03492

**Comment by ESanchezLozano** [comment]
Added, thanks :)

**Comment by impredicative** [comment]
IMHO, please avoid linking to the Arxiv PDF directly. Some readers only want to see the abstract or see citations, neither of which need the PDF. Please consider linking to the Arxiv HTML page only.
