### ISSUE TITLE
What is your license?

### ISSUE THREAD

**Issue by rex-yue-wu** [ESanchezLozano/GANnotation#10]
Can you specify your license? Want to check this before I use your pretrained model. 

Many thanks.

**Comment by ESanchezLozano** [comment]
Hi, 

Licence is BSD-3-Clause (https://opensource.org/licenses/BSD-3-Clause). Use is permitted for research purposes only. 

I will upload this on the README.md file including this information.

Many thanks.

**Comment by rex-yue-wu** [comment]
Many thanks
