### ISSUE TITLE
model.py vs. model_GAN.py 

### ISSUE THREAD

**Issue by YongGeunLee** [ESanchezLozano/GANnotation#14]
Generator class in the model.py file in the top-level folder implements "GANimization: Anatomically-aware Facial Animation from a Single Image." (Model to learn by dividing mask and image). However, Generator class in the model_GAN.py file in the Training folder implemented Generator in the basic Encoder-decoder structure, not the idea of the paper. What kind of generator should I use to learn from my custom data?

**Comment by ESanchezLozano** [comment]
Both are valid, you can replace the training by the one in model.py. The one in model.py corresponds to that of our FG 2020 paper where we presented GANnotation. The one in model_GAN.py in the training subpart is a more recent snippet that works well too.

**Comment by YongGeunLee** [comment]
Thank you for your reply
