### ISSUE TITLE
train procedure

### ISSUE THREAD

**Issue by voa18105** [ESanchezLozano/GANnotation#2]
Hello! Can you please provide train instructions?

**Comment by ESanchezLozano** [comment]
Hi,

The training code will be fully available with instructions in due time (soon ;) )

Thanks!

**Comment by voa18105** [comment]
@ESanchezLozano it would be cool, thank you!

**Comment by twmht** [comment]
@ESanchezLozano 

any update?

**Comment by ESanchezLozano** [comment]
@twmht I hope I will be able to make the training code available somehow soon, along with a new version of the pre-print. I'm sorry it is taking longer than expected.

**Comment by motkeg** [comment]
Hi,
I do some research on the GAN notation field , if you can upload the train instructions soon it will be very useful

**Comment by cbsudux** [comment]
@ESanchezLozano When will you be releasing the training code?

**Comment by ESanchezLozano** [comment]
@cbsudux a new version of the paper is now under peer-review. In any case, a whole new improved version of the code with training and testing will be uploaded at some point.

**Comment by cbsudux** [comment]
@ESanchezLozano Oh nice! Will you be uploading it soon? (next 1 month?)

**Comment by ESanchezLozano** [comment]
I am not sure this will possible, busy times ahead. But I promise I'll do my best to update it as soon as possible

**Comment by cbsudux** [comment]
Cool thanks

**Comment by XiaodanLi001** [comment]
Any updates about the training procedure?

**Comment by ESanchezLozano** [comment]
The training procedure will be uploaded after the upcoming deadlines. All code is being revisited and polished for its publication.

**Comment by interactivetech** [comment]
Thanks for adding the training scripts! @ESanchezLozano
