### ISSUE TITLE
reproduce

### ISSUE THREAD

**Issue by voa18105** [ESanchezLozano/GANnotation#3]
I've launched the code with your weights and tests... and it provided me the video. Not sure it is a face... Can you please provide any comments on this?

[test_1.zip](https://github.com/ESanchezLozano/GANnotation/files/2782990/test_1.zip)

**Comment by ESanchezLozano** [comment]
The whole demo is built to return a video for all the points contained in test_1.txt, if you dig a bit into the demo.py code you can find that the specific instruction is 

images, cropped_pts = myGAN.reenactment(image,points)

You can define points manually to be a matrix of 66 x 2 x num_of_images, where num_of_images can be even 1. Then the reenactment function will return the corresponding images, which you can display in any way of your convenience.

Hope this helps

**Comment by voa18105** [comment]
@ESanchezLozano Thank you for a prompt reply. I understand this, I've checked the code today... just... did you see the video I've uploaded? it is your image and your points worked in this way for me. No any changes from my side. I was expecting something more facial :-)

**Comment by voa18105** [comment]
@ESanchezLozano btw, I've tried your triple consistency loss with StarGAN and it does work pretty better than the original StarGAN. That is why it looked strange for me not to get any face with GANnotation

**Comment by ESanchezLozano** [comment]
> @ESanchezLozano btw, I've tried your triple consistency loss with StarGAN and it does work pretty better than the original StarGAN. That is why it looked strange for me not to get any face with GANnotation

Many thanks, it is good to hear this!

**Comment by voa18105** [comment]
@ESanchezLozano I found the reason, its my fault, I've used Python 2.7. Now it works! Thanks anyway for your attention.
