### ISSUE TITLE
StarGAN-with-Triple-Consistency-Loss

### ISSUE THREAD

**Issue by TJJTJJTJJ** [ESanchezLozano/GANnotation#6]
Hi:
     Thank you for your improvement in StarGAN-with-Triple-Consistency-Loss. It's very good. 
     I would to know that, in the process of one-many, if StarGAN-with-Triple-Consistency-Loss is better than StarGAN-without-Triple-Consistency-Loss? How about your opinion.

**Comment by TJJTJJTJJ** [comment]
I am expected to your code about training.

**Comment by ESanchezLozano** [comment]
The code for training StarGAN with the triple consistency loss is available here [https://github.com/ESanchezLozano/StarGAN-with-Triple-Consistency-Loss](https://github.com/ESanchezLozano/StarGAN-with-Triple-Consistency-Loss)

The code for training GANnotation will be available in due time :)

Thanks

**Comment by TJJTJJTJJ** [comment]
In your code, I see that Triple-Consistency-Loss is only available in single dataset. Now I want to use it in both datatsets to get better performance. How do you think my opinion? Or may you do some same work?

And in your code:
```python
if self.dataset == 'CelebA':
    c_org = label_org.clone()
    c_trg = label_trg.clone()
    c_third = label_third.clone()
elif self.dataset == 'RaFD':
    c_org = self.label2onehot(label_org, self.c_dim)
    c_trg = self.label2onehot(label_trg, self.c_dim)
    c_third = self.label2onehot(label_third, self.c_dim)
```
the last row you lost.

**Comment by ESanchezLozano** [comment]
Sure, I didn't go through the other database because I was having no access to RaFD, but the process is exactly the same.
