### ISSUE TITLE
I am confused about the sign of the formula in the paper

### ISSUE THREAD

**Issue by scutzzy** [ESanchezLozano/GANnotation#8]
At pixel loss, it has double vertical line with upper 2 and lower 2,is it means squared Euclidean norm? and at consistency loss with only upper 2, is it the same as pixel loss？and at Identity preserving loss, with only double vertical line, is it simply means Euclidean norm?

**Comment by ESanchezLozano** [comment]
The pixel loss is the typical MSE, though it can be replaced by an L1 norm error. MSE seems to make it a bit smoother whereas typically L1 norm seems to work better when properly combined with GANs. You might just observe some subtle differences in the pixel level. The identity preserving is L1 norm and the other two are L1 norm too. This shall be eventually corrected in the manuscript. Thanks for pointing this out. I hope this helps!
